### ISSUE TITLE
Generated anchor links for the same titles with different capitalization

### ISSUE THREAD

**Issue by lemichael** [dotnet/docs.cs-cz#13]
Hello! There is a small issue with generated anchor links in the documentation when two sections have the same title which differs only in capitalization. For instance, &lt;&lt; The "mm" custom format specifier &gt;&gt; and &lt;&lt; The "MM" custom format specifier &gt;&gt; are two distinct sections but both have the same anchor #the-mm-customer-format-specifier.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Vlastní řetězce formátu data a času](https://docs.microsoft.com/cs-cz/dotnet/standard/base-types/custom-date-and-time-format-strings#the-ffffff-custom-format-specifier)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs.cs-cz/blob/live/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Hello, @lemichael 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/11560

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
