### ISSUE TITLE
FIFO (First-in, First-in)

### ISSUE THREAD

**Issue by MartinSulcDotCz** [dotnet/docs.cs-cz#22]
Wrong:
ConcurrentQueue<T> | Implementace fronty FIFO (First-in, First-in), která je bezpečná pro přístup z více vláken.

Correct:
ConcurrentQueue<T> | Implementace fronty FIFO (First-in, First-**out**), která je bezpečná pro přístup z více vláken.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: b2a02e95-a17b-bfb0-c4ea-03f5f2d28907
* Version Independent ID: 647b6ea3-cde8-ba16-c9f7-c543c01517d9
* Content: [Kolekce se zabezpečenými vlákny](https://docs.microsoft.com/cs-cz/dotnet/standard/collections/thread-safe/)
* Content Source: [docs/standard/collections/thread-safe/index.md](https://github.com/dotnet/docs.cs-cz/blob/live/docs/standard/collections/thread-safe/index.md)
* Product: **dotnet**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hey @JasonCard - are you able to assist with this translation issue?

**Comment by JasonCard** [comment]
@MartinSulcDotCz @IEvangelist Thank you for reporting this issue. Czech content is mostly machine translated, and we are currently limited in our ability to permanently fix specific Machine Translation issues. I've made a temporary fix, so it's now currently fixed in live page, but it may revert the next time when there is a source update. We are working on improving the quality of machine translation and we appreciate your patience and understanding.
